CHERRY-PICK: E5071C mock: add mock for :SENS:SWEep:TYPE LINear
BUG=chrome-os-partner:20240
TEST=Manually execute e5071c_mock.py and test with following:
telnet localhost 5025
< :SENS:SWEep:TYPE SEGMent
< :SENS:SWEep:TYPE?
> SEGMent

< :SENS:SWEep:TYPE LINear
< :SENS:SWEep:TYPE?
> LINear

< :SENS:SWEep:TYPE POWer
Connection closed by foreign host.

Observed the mock side shows the following:
ValueError: Input ':SENS:SWEep:TYPE POWer' is not matching any.

Original Change-Id: I3b9f14b94e19abdeb21e15f40d45f948f51f6792
Original Reviewed-on: https://gerrit.chromium.org/gerrit/61052
Original Commit-Queue: Chun-Ta Lin <itspeter@google.com>
Original Reviewed-by: Chun-Ta Lin <itspeter@google.com>
Original Tested-by: Chun-Ta Lin <itspeter@google.com>
(cherry picked from commit df0e8b084bcc9436dc684866821d10d1ba9c3e96)

Change-Id: If6f980de0758e74b3c10e60fd5019d6fa1ee97cc
Reviewed-on: https://gerrit.chromium.org/gerrit/62275
Commit-Queue: Chun-Ta Lin <itspeter@google.com>
Reviewed-by: Chun-Ta Lin <itspeter@google.com>
Tested-by: Chun-Ta Lin <itspeter@google.com>